### ISSUE TITLE
Mod Suggestions for TNP Limitless: Refabricated

### ISSUE THREAD

**Issue by Gbergz** [The-Nexus-Project/Limitless-Refabricated#1]
Closed.

**Comment by odessadraekavik** [comment]
![https://i.imgur.com/TKEXKXp.png](https://i.imgur.com/TKEXKXp.png)
**Spectrum** https://www.curseforge.com/minecraft/mc-mods/spectrum

Spectrum is a story driven, exploration-based magic mod for Fabric focusing on the natural energies that flow in the world, represented in color.

**Comment by Rejnhard** [comment]
If you want some inspiration to mods/mods composition on fabric 1.18.2 I recommend to compare this modpack to similar in size big fabric modpack Deathdusk on website modpackindex. There are actually so many mods, it would make no sense to describe below dozen modifications. The way the fabric is optimalized gives a very big opportunity to bring in as many mods as possible without big perfomance losses.

**Comment by Gbergz** [comment]
@Rejnhard This is a mod suggestion page, not a place to mention other modpacks. Thanks though.

**Comment by odessadraekavik** [comment]
![image](https://user-images.githubusercontent.com/4887819/188318005-5b273971-bd22-44d0-a848-474510f8f9e2.png)
This mod is client side only, which adds a more vibrant ambience.

What's new?
- More sounds
- Smooth sound loops
- Variety of sounds for one region (changing from time to time)
- Reworked engine (now includes more options)

**AmbiantSounds 5 - Fabric** [https://www.curseforge.com/minecraft/mc-mods/ambientsounds](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)

**Comment by SineW4V3** [comment]
**EMI:** https://www.curseforge.com/minecraft/mc-mods/emi

**Replacement for REI**

-----------------------------------------------------------------------------------------------------------------------------------

What does EMI bring to the table?

Of course EMI comes with every feature you'd come to expect from the outset, viewing recipes, favoriting items, searching, and the like. But what's new that EMI offers?

- A craftable mode for quickly crafting any recipes you're able to make, usable by toggle or as a config for empty searches Recipes can be favorited with items, and also can be used to quickly craft at a button press

- A recipe tree for breaking down the cost of a complex craft, showing you every step, how many base ingredients you need, and what you'll have leftover

- A recipe tree crafting mode, counting up the materials and steps you need to be complete to finish a task, including synthetic favorites in your sidebar you can use to craft every step for exactly as much as you need

- Smart display of tags, with translations, models, and tooltips, showing you ingredients at a glance, such as "Planks" instead of slowly rotating through every plank in the game.

- Smart breakdowns of base costs, letting recipe trees automatically break down to base ingredients, and letting you define your own defaults as you play

- Tooltips for recipes, tags, and ingredients showing you what will be crafted, and what makes up an ingredient

- Binds for quick crafting straight into your inventory or cursor, one or many at a time, in conjunction with recipes favorites or the craftable mode

- A clean and modern API, built from the ground up to be simple, powerful, and suit all of EMI's features

- Zero third party dependencies. EMI only requires standard, first party Fabric/Quilt APIs

**Comment by Gbergz** [comment]
@SineW4V3 
Sorry, if I shut down this suggestion quickly, but I won't switch REI out. For reasons, indev stuff and other stuff.

**Comment by Supergod99** [comment]
![image](https://user-images.githubusercontent.com/20763323/191296630-b083d7d7-41a1-44db-a1b2-2353a4217dd6.png)

Mythic Metals is a minecaft mod all about finding new ores, smelting them into ingots and alloys, and turning them into your favorite tools and armor. 

The ores in this mod all cover their own slice of the underground. There are even some in The Nether and The End!

After gathering enough ores you can smelt them, blast them, or forge them with an Alloy Forge, into pretty metals or unique alloys.

Swords stronger than netherite, a pickaxe that can blast through an obsidian wall, and armor that grows over time. This is some of the gear you can find and craft using the metals. 

**Mythic Metals Fabric** - https://www.curseforge.com/minecraft/mc-mods/mythicmetals

**Comment by TachUDF** [comment]
**BetterNether and BetterEnd**
https://www.curseforge.com/minecraft/mc-mods/betternether
https://www.curseforge.com/minecraft/mc-mods/betterend
These two mods also need BCLib
https://www.curseforge.com/minecraft/mc-mods/bclib

**Comment by Gbergz** [comment]
@TachUDF Won't add due to the BCLib addon, breaks stuff. Sorry.

**Comment by noncom** [comment]
https://www.curseforge.com/minecraft/mc-mods/archon -- more magic!
https://www.curseforge.com/minecraft/mc-mods/liroth-revamped-fabric -- new dimension!

https://www.curseforge.com/minecraft/mc-mods/eden-ring -- dimensions! uh.. I wish.. if BCLib ever becomes more stable..

**Comment by PhantomEnderium** [comment]
Anyone remember Sync? [There's an unofficial Fabric Port for 1.18.2!](https://www.curseforge.com/minecraft/mc-mods/sync-fabric)

Create Shells that you can "transfer your mind too", essentially!

**Comment by Fnige** [comment]
https://www.curseforge.com/minecraft/mc-mods/amecs 
Keybinding mod so you can do stuff like Ctrl + A

https://www.curseforge.com/minecraft/mc-mods/better-biome-blend
Optimises biome blend at the sacrifice of forced 29x29 blend but its still very fast
